### ISSUE TITLE
Non Silk Touch pickaxe can mine spawners on Minecraft 1.14.4

### ISSUE THREAD

**Issue by Nico-Salamone** [oOBoomberOo/mineable_spawner#1]
Hi oOBoomberOo,

First one, thanks for your great data pack!
Second one, I find out pickaxes with that don't have the "Silk Touch" enchantment can mine spawners on Minecraft 1.14.4 (maybe also in previous versions).
To fix this, I edited the "data/minecraft/tags/loot_tables/blocks/spawner.json" file. You can find this fix on this [link](https://pastebin.com/gvfSR6sd).

Best regards,
Nico Salamone

**Comment by oOBoomberOo** [comment]
First of all, sorry for the very late reply. I just found out about this since I apparently wasn't subscribed to my own repository.
And I'll be closing the issue since a fix has already been pushed to the 2.0 version.
